### ISSUE TITLE
Incorrect rounding explanation (answer) for adding a zero

### ISSUE THREAD

**Issue by mole6e23** [WeBWorK-for-Chemistry/WeBWorKChemistry#3]
If you see any more problems with this, let me know!  And thank you for diagnosing this!  It would have been awful to track this down myself.  I am still quite naive about Perl in a few places.

_Originally posted by @limefrogyank in https://github.com/WeBWorK-for-Chemistry/WeBWorKChemistry/issues/1#issuecomment-1663281862_

This seemed to fix the error with the incorrect formatting that I flagged in the original post, thank you!

One issue is still remaining that the number 820450970 rounded to 7 significant figures is not getting turned into scientific notation in the explanation, as it needs to (820451000 has only 6 significant figures).

A second issue that I am seeing in the file from 2 August is that the number 24325 when rounded to 6 significant figures shows an incorrect answer in the explanation. The explanation is fine since it says that a zero needs to be added, but no zero gets added (see screen shot attached).
  
In both of these cases, the internal representation of the number is correctly being calculated and checked by the answer checker (I must enter 24325.0 to get the problem correct), it is just the explanation that is not showing correctly. 

![rounding by adding zero 3 Aug 23](https://user-images.githubusercontent.com/136017750/258188843-7748e4bc-9f2b-4cc5-9486-fe5cdbb53712.png)

**Comment by limefrogyank** [comment]
Since you're actually using these I need to let you know the following.  (Also, I need to come up with a version release scheme so we can announce these changes properly.) 

I had to change the API for `generateSfRoundingExplanation`.  Sorry about that but it was different from the others and I had to choose one way to format it.  Instead of using `->{TeX}` or `->{text}`, it now by default outputs LaTeX.  To have it output plain text, I added a key to the 2nd optional parameter like so:
```
$ans1->generateSfRoundingExplanation($sf1); # outputs LaTeX format
$ans1->generateSfRoundingExplanation($sf1,{plainText=>1}); # outputs string format
```
All of the "generate...Explanation" should work that way now.  Some of the demo pages have been updated with examples of how to use them. 

As far as these two issues are concerned, I'll work on them soon.

**Comment by limefrogyank** [comment]
![image](https://github.com/WeBWorK-for-Chemistry/WeBWorKChemistry/assets/7821384/4eb26a3f-cc89-4107-8f6f-11ec073e5480)

I seem to have fixed the first remaining issue.   This code is what I used to check it.  If that's not what you're doing and it's still wrong, show me an example please.
```
$test = InexactValue(820450970,8);
$e = $test->generateSfRoundingExplanation(7);
BEGIN_PGML_SOLUTION

[``` [$e] ```]

END_PGML_SOLUTION
```
![image](https://github.com/WeBWorK-for-Chemistry/WeBWorKChemistry/assets/7821384/ce434a83-4bbf-4353-a66f-e7363ccfeeb4)

The second issue was due to the explanation using the original value for the final "rounded" value.  Instead, I made a copy of the original value and forced it to adopt the new number of sig figs.  I'm displaying this value at the end and it seems to work.
```
$test2 = InexactValue(24325,5);
$e2 = $test2->generateSfRoundingExplanation(6);
BEGIN_PGML_SOLUTION

[``` [$e2] ```]

END_PGML_SOLUTION
```
